<?php
$form = $this->form;

$form->prepare();

$form->setAttribute( 'class', 'form-horizontal' )
    ->setAttribute( 'role', 'form' );

$form->get( 'programs' )->setLabelAttributes( [
    'style' => 'font-weight:600;'
] );

$submitElement = $form->get( 'submit' );
$submitElement->setAttributes( [
    'class' => 'btn btn-primary'
] );

echo $this->form()->openTag( $form );
?>
<div class="col-sm-6 col-md-8">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5><?php echo $this->translate( 'Basic Data' ); ?></h5>
        </div>
        <div class="ibox-content">
            <?php
            echo $this->CurrentAlerts();
            echo $this->Alerts();

            echo $this->formElement( $form->get( 'id' ) );
            echo $this->formElement( $form->get( 'csrf' ) );
            echo $this->formRow( $form->get( 'subject_areas_id' ), null, null, 'form/row' );
            echo $this->formRow( $form->get( 'title' ), null, null );
            echo $this->formRow( $form->get( 'title_short' ), null, null );
            echo $this->formRow( $form->get( 'level' ), null, null );
            echo $this->formRow( $form->get( 'school_level' ), null, null );
            ?>
            <div class="form-group">
                <div class="col-lg-10 col-md-9 col-sm-8 col-lg-offset-2 col-md-offset-3 col-sm-offset-4">
                    <?php
                    echo $this->formElement( $submitElement );
                    echo $this->Html()->linkButton( 'Cancel', $this->url( 'subjects' ), [ 'color' => 'danger',
                        'class' => 'm-l-xs' ] );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-6 col-md-4">
    <div class="ibox float-e-margins traning-programs-list">
        <div class="ibox-title">
            <h5><?php echo $this->formLabel( $form->get( 'programs' ) ) /* $form->get( 'programs' )->getLabel() */; ?></h5>
            <div class="ibox-tools">
                <?php echo $this->Html()->linkButton( 'Add', 'javascript:;', ['icon'        => 'plus',
                    'size'        => 'xs', 'data-action' => 'add-program' ] );
                ?>
            </div>
        </div>
        <div class="ibox-content">
            <?php
            $this->formRow()->setPartial( 'partial/program_row.phtml' );
            echo $this->formCollection()
                ->setWrapper(
                    '<div class="program">%1$s%3$s<div class="program-delete">'
                    . ( $this->isGranted( 'subjects.programs.delete' ) ?
                        $this->Html()->button( '', [
                            'color'       => 'danger',
                            'size'        => 'sm',
                            'icon'        => 'trash',
                            'data-action' => 'delete-subject-program',
                            'style'       => 'font-size:14px'
                        ] ) :
                        '' )
                    . '</div></div>'
                )->render( $form->get( 'programs' ) );
            ?>
        </div>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>
<script>
<?php ob_start(); ?>
    jQuery( document ).ready( function ( $ ) {
<?php if ( $form->get( 'level' )->getAttribute( 'readonly' ) !== 'readonly' ) : ?>
            $( '#subject-level' ).incdescfield( {
                isAllowedNegative: false,
                max: 13,
                style: { 'width': '100px' }
            } );
<?php endif; ?>

        $( '[data-action="add-program"]' ).on( 'click', function ( event ) {
            event.preventDefault( );
            var currentCount = $( '.traning-programs-list > .ibox-content > .program > .program > .subject-program-id' ).length,
                template = $( '.traning-programs-list > .ibox-content > .program > span' ).data( 'template' );
            template = template.replace( /__index__/g, currentCount );
            $( '.traning-programs-list > .ibox-content > .program' ).append( template );
            $( '.traning-programs-list > .ibox-content > .program > .program:last .subject-program-subjects-id' ).val( $( '#subject-id' ).val() );
        } );

        $( document ).on( 'click', '[data-action="delete-subject-program"]', function ( event ) {
            var $program = $( this ).closest( '.program' );

            $program.deleteConfirmationRow( {
                deleteConfirmationTime: 8,
                changeStatusTime: 3,
                deleteUrl: '/subjects/deleteprogram',
                additionalData: { subject_id: $( '#subject-id' ).val() }
            } );
            $program.deleteConfirmationRow( 'showDeleteConfirmationRow', $program.find( '.subject-program-id' ).val() );
        } );

        $( '.i-checks' ).iCheck( {
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        } );
    } );
<?php
$script = ob_get_contents();
ob_end_clean();
?>

</script>

<style>
    .program > .program{
        border: 1px solid #bbb;
        padding:10px;
        margin-bottom: 10px;
        margin-right: 30px;
        position: relative;
    }

    .program > .program > .program-delete{
        font-size:1.5em;
        display: block;
        position: absolute;
        top: -1px;
        right: -50px;
        padding: 1px 10px;
    }

    .program > .program-delete{
        display: none;
    }
</style>

<?php
$this->headLink()->appendStylesheet( $this->basePath() . '/js/plugins/incdescfield/css/incdescfield.css' )
    ->appendStylesheet( $this->basePath() . '/css/plugins/iCheck/custom.css' )
//    ->appendStylesheet( $this->basePath() . '/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' )
;
$this->inlineScript()->appendFile( $this->basePath() . '/js/plugins/incdescfield/js/jquery.incdescfield.js' )
    ->appendFile( $this->basePath() . '/js/plugins/iCheck/icheck.min.js' )
    ->appendFile( $this->basePath() . '/js/plugins/deleteConfirmationRow/jquery.deleteConfirmationRow.js' )
    ->appendScript( $script );
